version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/my-sample-app
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      runas: root
