version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - mkdir -p dist
      - cp -r index.html server.js package.json node_modules dist/
      - cp appspec.yml dist/
      - cp -r scripts dist/
artifacts:
  base-directory: dist
  files:
    - '**/*'
