version: 0.2
phases:
  build:
    commands:
      - echo "Packaging artifact..."
      - mkdir -p dist
      - zip -r dist/latest.zip . -x dist/\*
      - aws s3 cp dist/latest.zip s3://$ARTIFACT_BUCKET/latest.zip